### ISSUE TITLE
Map Activity element is empty when adding a new dashboard

### ISSUE THREAD

**Issue by rabee333** [CatalystCode/ibex-dashboard#277]
Added a new dashboard with the following settings:
appId: "4d567b3c-e52c-4139-8e56-8e573e55a06c"
apiKey: "tn6hhxs60afz4yzd7cp2nreph1wja3ecxtflq8rs" 

The Map Activity element was empty and it shows the hovering circle all the time. When clicking on its Settings icon (the gear icon) on the upper left side of the component, it shows the following error:
"Element id error
Use the same id for the element and data source to unwind the query and data."

When pressing F12 and refreshing the page, getting the following error in the console:

HTML1300: Navigation occurred.
bot_analytics_dashboard2
SCRIPT5: Access is denied.

bot_analytics_dashboard2 (1,1)
Current window: localhost/dashboard/bot_analytics_dashboard2
ReferenceError: A store named SettingsStore already exists, double check your store names or pass in your own custom identifier for each store
main.90c1f23b.js (19,26682)
   {
      [functions]: ,
      __proto__: { },
      message: "A store named SettingsStore already exists, double check your store names or pass in your own custom identifier for each store",
      name: "ReferenceError",
      stack: "ReferenceError: A store named SettingsStore already exists, double check your store names or pass in your own custom identifier for each store
   at a (http://localhost:4000/static/js/main.90c1f23b.js:19:26682)
   at e (http://localhost:4000/static/js/main.90c1f23b.js:57:4001)
   at Anonymous function (http://localhost:4000/static/js/main.90c1f23b.js:91:23045)
   at t (http://localhost:4000/static/js/main.90c1f23b.js:1:95)
   at Anonymous function (http://localhost:4000/static/js/main.90c1f23b.js:88:28898)
   at t (http://localhost:4000/static/js/main.90c1f23b.js:1:95)
   at Anonymous function (http://localhost:4000/static/js/main.90c1f23b.js:56:18644)
   at t (http://localhost:4000/static/js/main.90c1f23b.js:1:95)
   at Anonymous function (http://localhost:4000/static/js/main.90c1f23b.js:88:8665)
   at t (http://localhost:4000/static/js/main.90c1f23b.js:1:95)
   at Anonymous function (http://localhost:4000/static/js/main.90c1f23b.js:91:18757)
   at t (http://localhost:4000/static/js/main.90c1f23b.js:1:95)
   at Anonymous function (http://localhost:4000/static/js/main.90c1f23b.js:91:21117)
   at t (http://localhost:4000/static/js/main.90c1f23b.js:1:95)
   at Anonymous function (http://localhost:4000/static/js/main.90c1f23b.js:91:18204)
   at t (http://localhost:4000/static/js/main.90c1f23b.js:1:95)
   at Anonymous function (http://localhost:4000/static/js/main.90c1f23b.js:1:488)
   at t (http://localhost:4000/static/js/main.90c1f23b.js:1:95)
   at Anonymous function (http://localhost:4000/static/js/main.90c1f23b.js:1:168)
   at Global code (http://localhost:4000/static/js/main.90c1f23b.js:1:1)"
   }

**Comment by morsh** [comment]
@eladiw - This looks like the same problem you were having. Do you think it's related?

**Comment by eladiw** [comment]
looks like the same issue.

**Comment by morsh** [comment]
Closing on duplicate #272
