### ISSUE TITLE
On integrate Active directory missing email error

### ISSUE THREAD

**Issue by CristianPQ** [CatalystCode/ibex-dashboard#353]
```
Error: No email found
    at Strategy._verify (/.../bot_analytic_dashboard/server/routes/auth.js:80:21)
    at onProfileLoaded (/.../bot_analytic_dashboard/server/node_modules/passport-azure-ad/lib/oidcstrategy.js:124:27)
    at Strategy._authCodeFlowHandler.self._getAccessTokenBySecretOrAssertion.self._idTokenHandler.oauth2.get.ex (/.../bot_analytic_dashboard/server/node_modules/passport-azure-ad/lib/oidcstrategy.js:1171:18)
    at passBackControl (/.../bot_analytic_dashboard/server/node_modules/oauth/lib/oauth2.js:125:9)
    at IncomingMessage.<anonymous> (/.../bot_analytic_dashboard/server/node_modules/oauth/lib/oauth2.js:143:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
Piece of code where it fails:
```
 function(iss, sub, profile, accessToken, refreshToken, done) {
      
      profile.email = profile.email || profile.upn;

      console.log(`passport profile: ${profile.email}`);

      if (!profile.email) {
        return done(new Error("No email found"), null); // throws that error
      }
```

Looking for a reason on google I've found that there have been some changes on 3.0 version of passportAzureAD, more info on the link below.
[https://github.com/AzureADQuickStarts/WebApp-OpenIDConnect-NodeJS/issues/5#issuecomment-261040857](url)

**Comment by morsh** [comment]
@CristianPQ - Don't you receive back a upn field instead?

**Comment by CristianPQ** [comment]
@morsh - nope, I see a black page with the error.ç

Is it solved in some branch?

**Comment by morsh** [comment]
I mean, when you debug the following line:
`profile.email = profile.email || profile.upn;`

**Comment by CristianPQ** [comment]
pofile.email is undefined and profile.upn is undefined too.

**Comment by CristianPQ** [comment]
There is an object inside profile, profile._json which has an "email".
